[package]
name = "conductor_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conductor_derive = { path = "../conductor_derive" }
conductor_shared = { path = "../conductor_shared" }